Repository openAOD/C-PatternHouse, pull requests merged in 2021-12, with the labels that each got.

#677 Added code for pyramid pattern from 1 to 20.
  Pyramid Patterns/pyramidpattern1.c
  Pyramid Patterns/pyramidpattern10.c
  Pyramid Patterns/pyramidpattern11.c
  Pyramid Patterns/pyramidpattern12.c
  Pyramid Patterns/pyramidpattern13.c
  Pyramid Patterns/pyramidpattern14.c
  Pyramid Patterns/pyramidpattern15.c
  Pyramid Patterns/pyramidpattern16.c
  Pyramid Patterns/pyramidpattern17.c
  Pyramid Patterns/pyramidpattern18.c
  Pyramid Patterns/pyramidpattern19.c
  Pyramid Patterns/pyramidpattern2.c
  Pyramid Patterns/pyramidpattern20.c
  Pyramid Patterns/pyramidpattern3.c
  Pyramid Patterns/pyramidpattern4.c
  Pyramid Patterns/pyramidpattern5.c
  Pyramid Patterns/pyramidpattern6.c
  Pyramid Patterns/pyramidpattern7.c
  Pyramid Patterns/pyramidpattern8.c
  Pyramid Patterns/pyramidpattern9.c
Labels: SWoC-21, easy

#679 Pattern 21 to 40
  Pyramid Patterns/pyramidpattern21.c
  Pyramid Patterns/pyramidpattern22.c
  Pyramid Patterns/pyramidpattern23.c
  Pyramid Patterns/pyramidpattern24.c
  Pyramid Patterns/pyramidpattern25.c
  Pyramid Patterns/pyramidpattern26.c
  Pyramid Patterns/pyramidpattern27.c
  Pyramid Patterns/pyramidpattern28.c
  Pyramid Patterns/pyramidpattern29.c
  Pyramid Patterns/pyramidpattern30.c
  Pyramid Patterns/pyramidpattern31.c
  Pyramid Patterns/pyramidpattern32.c
  Pyramid Patterns/pyramidpattern33.c
  Pyramid Patterns/pyramidpattern34.c
  Pyramid Patterns/pyramidpattern35.c
  Pyramid Patterns/pyramidpattern36.c
  Pyramid Patterns/pyramidpattern37.c
  Pyramid Patterns/pyramidpattern38.c
  Pyramid Patterns/pyramidpattern39.c
  Pyramid Patterns/pyramidpattern40.c
Labels: SWoC-21, easy

#680 Added code for pyramid pattern from 41 to 80.
  Pyramid Patterns/pyramidpattern41.c
  Pyramid Patterns/pyramidpattern42.c
  Pyramid Patterns/pyramidpattern43.c
  Pyramid Patterns/pyramidpattern44.c
  Pyramid Patterns/pyramidpattern45.c
  Pyramid Patterns/pyramidpattern46.c
  Pyramid Patterns/pyramidpattern47.c
  Pyramid Patterns/pyramidpattern48.c
  Pyramid Patterns/pyramidpattern49.c
  Pyramid Patterns/pyramidpattern50.c
  Pyramid Patterns/pyramidpattern51.c
  Pyramid Patterns/pyramidpattern52.c
  Pyramid Patterns/pyramidpattern53.c
  Pyramid Patterns/pyramidpattern54.c
  Pyramid Patterns/pyramidpattern55.c
  Pyramid Patterns/pyramidpattern56.c
  Pyramid Patterns/pyramidpattern57.c
  Pyramid Patterns/pyramidpattern58.c
  Pyramid Patterns/pyramidpattern59.c
  Pyramid Patterns/pyramidpattern60.c
  Pyramid Patterns/pyramidpattern61.c
  Pyramid Patterns/pyramidpattern62.c
  Pyramid Patterns/pyramidpattern63.c
  Pyramid Patterns/pyramidpattern64.c
  Pyramid Patterns/pyramidpattern65.c
  Pyramid Patterns/pyramidpattern66.c
  Pyramid Patterns/pyramidpattern67.c
  Pyramid Patterns/pyramidpattern68.c
  Pyramid Patterns/pyramidpattern69.c
  Pyramid Patterns/pyramidpattern70.c
  Pyramid Patterns/pyramidpattern71.c
  Pyramid Patterns/pyramidpattern72.c
  Pyramid Patterns/pyramidpattern73.c
  Pyramid Patterns/pyramidpattern74.c
  Pyramid Patterns/pyramidpattern75.c
  Pyramid Patterns/pyramidpattern76.c
  Pyramid Patterns/pyramidpattern77.c
  Pyramid Patterns/pyramidpattern78.c
  Pyramid Patterns/pyramidpattern79.c
  Pyramid Patterns/pyramidpattern80.c
Labels: SWoC-21, hard

#691 Added code for pyramid pattern from 81 to 93.
  Pyramid Patterns/pyramidpattern81.c
  Pyramid Patterns/pyramidpattern82.c
  Pyramid Patterns/pyramidpattern83.c
  Pyramid Patterns/pyramidpattern84.c
  Pyramid Patterns/pyramidpattern85.c
  Pyramid Patterns/pyramidpattern86.c
  Pyramid Patterns/pyramidpattern87.c
  Pyramid Patterns/pyramidpattern88.c
  Pyramid Patterns/pyramidpattern89.c
  Pyramid Patterns/pyramidpattern90.c
  Pyramid Patterns/pyramidpattern91.c
  Pyramid Patterns/pyramidpattern92.c
  Pyramid Patterns/pyramidpattern93.c
Labels: SWoC-21, beginner

#692 numeric patterns 1 to 20
  Numeric Patterns/numericpattern1.c
  Numeric Patterns/numericpattern10.c
  Numeric Patterns/numericpattern11.c
  Numeric Patterns/numericpattern12.c
  Numeric Patterns/numericpattern13.c
  Numeric Patterns/numericpattern14.c
  Numeric Patterns/numericpattern15.c
  Numeric Patterns/numericpattern16.c
  Numeric Patterns/numericpattern17.c
  Numeric Patterns/numericpattern18.c
  Numeric Patterns/numericpattern19.c
  Numeric Patterns/numericpattern2.c
  Numeric Patterns/numericpattern20.c
  Numeric Patterns/numericpattern3.c
  Numeric Patterns/numericpattern4.c
  Numeric Patterns/numericpattern5.c
  Numeric Patterns/numericpattern6.c
  Numeric Patterns/numericpattern7.c
  Numeric Patterns/numericpattern8.c
  Numeric Patterns/numericpattern9.c
Labels: SWoC-21, easy

#693 Added 40 patterns
  Series Patterns/seriespattern1.c
  Series Patterns/seriespattern2.c
  Series Patterns/seriespattern3.c
  Series Patterns/seriespattern4.c
  Series Patterns/seriespattern5.c
  Series Patterns/seriespattern6.c
  Series Patterns/seriespattern7.c
  Series Patterns/seriespattern8.c
  Series Patterns/seriespattern9.c
  Spiral Patterns/spiralpattern1.c
  Spiral Patterns/spiralpattern2.c
  Spiral Patterns/spiralpattern3.c
  Spiral Patterns/spiralpattern4.c
  Wave Patterns/wavepattern1.c
  Wave Patterns/wavepattern10.c
  Wave Patterns/wavepattern11.c
  Wave Patterns/wavepattern12.c
  Wave Patterns/wavepattern13.c
  Wave Patterns/wavepattern14.c
  Wave Patterns/wavepattern15.c
  Wave Patterns/wavepattern16.c
  Wave Patterns/wavepattern17.c
  Wave Patterns/wavepattern18.c
  Wave Patterns/wavepattern19.c
  Wave Patterns/wavepattern2.c
  Wave Patterns/wavepattern20.c
  Wave Patterns/wavepattern21.c
  Wave Patterns/wavepattern22.c
  Wave Patterns/wavepattern23.c
  Wave Patterns/wavepattern24.c
  Wave Patterns/wavepattern25.c
  Wave Patterns/wavepattern26.c
  Wave Patterns/wavepattern27.c
  Wave Patterns/wavepattern3.c
  Wave Patterns/wavepattern4.c
  Wave Patterns/wavepattern5.c
  Wave Patterns/wavepattern6.c
  Wave Patterns/wavepattern7.c
  Wave Patterns/wavepattern8.c
  Wave Patterns/wavepattern9.c
Labels: SWoC-21, hard

#695 Added 40 patterns
  Alphabetic Patterns/alphabeticpattern1.c
  Alphabetic Patterns/alphabeticpattern10.c
  Alphabetic Patterns/alphabeticpattern11.c
  Alphabetic Patterns/alphabeticpattern12.c
  Alphabetic Patterns/alphabeticpattern13.c
  Alphabetic Patterns/alphabeticpattern14.c
  Alphabetic Patterns/alphabeticpattern15.c
  Alphabetic Patterns/alphabeticpattern16.c
  Alphabetic Patterns/alphabeticpattern17.c
  Alphabetic Patterns/alphabeticpattern18.c
  Alphabetic Patterns/alphabeticpattern19.c
  Alphabetic Patterns/alphabeticpattern2.c
  Alphabetic Patterns/alphabeticpattern20.c
  Alphabetic Patterns/alphabeticpattern21.c
  Alphabetic Patterns/alphabeticpattern22.c
  Alphabetic Patterns/alphabeticpattern23.c
  Alphabetic Patterns/alphabeticpattern24.c
  Alphabetic Patterns/alphabeticpattern25.c
  Alphabetic Patterns/alphabeticpattern3.c
  Alphabetic Patterns/alphabeticpattern4.c
  Alphabetic Patterns/alphabeticpattern5.c
  Alphabetic Patterns/alphabeticpattern6.c
  Alphabetic Patterns/alphabeticpattern7.c
  Alphabetic Patterns/alphabeticpattern8.c
  Alphabetic Patterns/alphabeticpattern9.c
  String Patterns/stringpattern1.c
  String Patterns/stringpattern10.c
  String Patterns/stringpattern11.c
  String Patterns/stringpattern12.c
  String Patterns/stringpattern13.c
  String Patterns/stringpattern14.c
  String Patterns/stringpattern15.c
  String Patterns/stringpattern2.c
  String Patterns/stringpattern3.c
  String Patterns/stringpattern4.c
  String Patterns/stringpattern5.c
  String Patterns/stringpattern6.c
  String Patterns/stringpattern7.c
  String Patterns/stringpattern8.c
  String Patterns/stringpattern9.c
Labels: SWoC-21, hard
