Repository openAOD/C-PatternHouse, pull requests merged in 2022-01, with the labels that each got.

#748 40 symbol patterns added
  Symbol Patterns/symbolpattern21.c
  Symbol Patterns/symbolpattern22.c
  Symbol Patterns/symbolpattern23.c
  Symbol Patterns/symbolpattern24.c
  Symbol Patterns/symbolpattern25.c
  Symbol Patterns/symbolpattern26.c
  Symbol Patterns/symbolpattern27.c
  Symbol Patterns/symbolpattern28.c
  Symbol Patterns/symbolpattern29.c
  Symbol Patterns/symbolpattern30.c
  Symbol Patterns/symbolpattern31.c
  Symbol Patterns/symbolpattern32.c
  Symbol Patterns/symbolpattern33.c
  Symbol Patterns/symbolpattern34.c
  Symbol Patterns/symbolpattern35.c
  Symbol Patterns/symbolpattern36.c
  Symbol Patterns/symbolpattern37.c
  Symbol Patterns/symbolpattern38.c
  Symbol Patterns/symbolpattern39.c
  Symbol Patterns/symbolpattern40.c
  Symbol Patterns/symbolpattern41.c
  Symbol Patterns/symbolpattern42.c
  Symbol Patterns/symbolpattern43.c
  Symbol Patterns/symbolpattern44.c
  Symbol Patterns/symbolpattern45.c
  Symbol Patterns/symbolpattern46.c
  Symbol Patterns/symbolpattern47.c
  Symbol Patterns/symbolpattern48.c
  Symbol Patterns/symbolpattern49.c
  Symbol Patterns/symbolpattern50.c
  Symbol Patterns/symbolpattern51.c
  Symbol Patterns/symbolpattern52.c
  Symbol Patterns/symbolpattern53.c
  Symbol Patterns/symbolpattern54.c
  Symbol Patterns/symbolpattern55.c
  Symbol Patterns/symbolpattern56.c
  Symbol Patterns/symbolpattern57.c
  Symbol Patterns/symbolpattern58.c
  Symbol Patterns/symbolpattern59.c
  Symbol Patterns/symbolpattern60.c
Labels: SWoC-21, hard

#747 40 patterns added
  Alphabetic Patterns/alphabeticpattern26.c
  Alphabetic Patterns/alphabeticpattern27.c
  Alphabetic Patterns/alphabeticpattern28.c
  Alphabetic Patterns/alphabeticpattern29.c
  Alphabetic Patterns/alphabeticpattern30.c
  Alphabetic Patterns/alphabeticpattern31.c
  Alphabetic Patterns/alphabeticpattern32.c
  Alphabetic Patterns/alphabeticpattern33.c
  Alphabetic Patterns/alphabeticpattern34.c
  Alphabetic Patterns/alphabeticpattern35.c
  Alphabetic Patterns/alphabeticpattern58.c
  Alphabetic Patterns/alphabeticpattern59.c
  Alphabetic Patterns/alphabeticpattern60.c
  Alphabetic Patterns/alphabeticpattern61.c
  Alphabetic Patterns/alphabeticpattern62.c
  Alphabetic Patterns/alphabeticpattern63.c
  Alphabetic Patterns/alphabeticpattern64.c
  Alphabetic Patterns/alphabeticpattern65.c
  Alphabetic Patterns/alphabeticpattern72.c
  Alphabetic Patterns/alphabeticpattern73.c
  Alphabetic Patterns/alphabeticpattern74.c
  Alphabetic Patterns/alphabeticpattern75.c
  Alphabetic Patterns/alphabeticpattern76.c
  Alphabetic Patterns/alphabeticpattern77.c
  Alphabetic Patterns/alphabeticpattern78.c
  Alphabetic Patterns/alphabeticpattern79.c
  Alphabetic Patterns/alphabeticpattern80.c
  Alphabetic Patterns/alphabeticpattern81.c
  Alphabetic Patterns/alphabeticpattern82.c
  Alphabetic Patterns/alphabeticpattern83.c
  Alphabetic Patterns/alphabeticpattern84.c
  Alphabetic Patterns/alphabeticpattern85.c
  Alphabetic Patterns/alphabeticpattern86.c
  Alphabetic Patterns/alphabeticpattern87.c
  Alphabetic Patterns/alphabeticpattern88.c
  Alphabetic Patterns/alphabeticpattern89.c
  Alphabetic Patterns/alphabeticpattern90.c
  Alphabetic Patterns/alphabeticpattern91.c
  Alphabetic Patterns/alphabeticpattern92.c
  Alphabetic Patterns/alphabeticpattern93.c
Labels: SWoC-21, hard

#694 numeric pattern 21 to 40
  Numeric Patterns/numericpattern21.c
  Numeric Patterns/numericpattern22.c
  Numeric Patterns/numericpattern23.c
  Numeric Patterns/numericpattern24.c
  Numeric Patterns/numericpattern25.c
  Numeric Patterns/numericpattern26.c
  Numeric Patterns/numericpattern27.c
  Numeric Patterns/numericpattern28.c
  Numeric Patterns/numericpattern29.c
  Numeric Patterns/numericpattern30.c
  Numeric Patterns/numericpattern31.c
  Numeric Patterns/numericpattern32.c
  Numeric Patterns/numericpattern33.c
  Numeric Patterns/numericpattern34.c
  Numeric Patterns/numericpattern35.c
  Numeric Patterns/numericpattern36.c
  Numeric Patterns/numericpattern37.c
  Numeric Patterns/numericpattern38.c
Labels: SWoC-21, beginner

#811 Added 40 Numeric Patterns 101-140
  Numeric Patterns/numericpattern101.c
  Numeric Patterns/numericpattern102.c
  Numeric Patterns/numericpattern103.c
  Numeric Patterns/numericpattern104.c
  Numeric Patterns/numericpattern105.c
  Numeric Patterns/numericpattern106.c
  Numeric Patterns/numericpattern107.c
  Numeric Patterns/numericpattern108.c
  Numeric Patterns/numericpattern109.c
  Numeric Patterns/numericpattern110.c
  Numeric Patterns/numericpattern111.c
  Numeric Patterns/numericpattern112.c
  Numeric Patterns/numericpattern113.c
  Numeric Patterns/numericpattern114.c
  Numeric Patterns/numericpattern115.c
  Numeric Patterns/numericpattern116.c
  Numeric Patterns/numericpattern117.c
  Numeric Patterns/numericpattern118.c
  Numeric Patterns/numericpattern119.c
  Numeric Patterns/numericpattern120.c
  Numeric Patterns/numericpattern121.c
  Numeric Patterns/numericpattern122.c
  Numeric Patterns/numericpattern123.c
  Numeric Patterns/numericpattern124.c
  Numeric Patterns/numericpattern125.c
  Numeric Patterns/numericpattern126.c
  Numeric Patterns/numericpattern127.c
  Numeric Patterns/numericpattern128.c
  Numeric Patterns/numericpattern129.c
  Numeric Patterns/numericpattern130.c
  Numeric Patterns/numericpattern131.c
  Numeric Patterns/numericpattern132.c
  Numeric Patterns/numericpattern133.c
  Numeric Patterns/numericpattern134.c
  Numeric Patterns/numericpattern135.c
  Numeric Patterns/numericpattern136.c
  Numeric Patterns/numericpattern137.c
  Numeric Patterns/numericpattern138.c
  Numeric Patterns/numericpattern139.c
  Numeric Patterns/numericpattern140.c
Labels: SWoC-21, hard

#810 40 symbol patterns added
  Symbol Patterns/symbolpattern100.c
  Symbol Patterns/symbolpattern101.c
  Symbol Patterns/symbolpattern102.c
  Symbol Patterns/symbolpattern103.c
  Symbol Patterns/symbolpattern104.c
  Symbol Patterns/symbolpattern105.c
  Symbol Patterns/symbolpattern106.c
  Symbol Patterns/symbolpattern107.c
  Symbol Patterns/symbolpattern108.c
  Symbol Patterns/symbolpattern109.c
  Symbol Patterns/symbolpattern110.c
  Symbol Patterns/symbolpattern71.c
  Symbol Patterns/symbolpattern72.c
  Symbol Patterns/symbolpattern73.c
  Symbol Patterns/symbolpattern74.c
  Symbol Patterns/symbolpattern75.c
  Symbol Patterns/symbolpattern76.c
  Symbol Patterns/symbolpattern77.c
  Symbol Patterns/symbolpattern78.c
  Symbol Patterns/symbolpattern79.c
  Symbol Patterns/symbolpattern80.c
  Symbol Patterns/symbolpattern81.c
  Symbol Patterns/symbolpattern82.c
  Symbol Patterns/symbolpattern83.c
  Symbol Patterns/symbolpattern84.c
  Symbol Patterns/symbolpattern85.c
  Symbol Patterns/symbolpattern86.c
  Symbol Patterns/symbolpattern87.c
  Symbol Patterns/symbolpattern88.c
  Symbol Patterns/symbolpattern89.c
  Symbol Patterns/symbolpattern90.c
  Symbol Patterns/symbolpattern91.c
  Symbol Patterns/symbolpattern92.c
  Symbol Patterns/symbolpattern93.c
  Symbol Patterns/symbolpattern94.c
  Symbol Patterns/symbolpattern95.c
  Symbol Patterns/symbolpattern96.c
  Symbol Patterns/symbolpattern97.c
  Symbol Patterns/symbolpattern98.c
  Symbol Patterns/symbolpattern99.c
Labels: SWoC-21, hard

#898 Added 21 Numeric Patterns 141-161
  Numeric Patterns/numericpattern141.c
  Numeric Patterns/numericpattern142.c
  Numeric Patterns/numericpattern143.c
  Numeric Patterns/numericpattern144.c
  Numeric Patterns/numericpattern145.c
  Numeric Patterns/numericpattern146.c
  Numeric Patterns/numericpattern147.c
  Numeric Patterns/numericpattern148.c
  Numeric Patterns/numericpattern149.c
  Numeric Patterns/numericpattern150.c
  Numeric Patterns/numericpattern151.c
  Numeric Patterns/numericpattern152.c
  Numeric Patterns/numericpattern153.c
  Numeric Patterns/numericpattern154.c
  Numeric Patterns/numericpattern155.c
  Numeric Patterns/numericpattern156.c
  Numeric Patterns/numericpattern157.c
  Numeric Patterns/numericpattern158.c
  Numeric Patterns/numericpattern159.c
  Numeric Patterns/numericpattern160.c
  Numeric Patterns/numericpattern161.c
Labels: SWoC-21, easy

#899 10 patterns added
  Symbol Patterns/symbolpattern61.c
  Symbol Patterns/symbolpattern62.c
  Symbol Patterns/symbolpattern63.c
  Symbol Patterns/symbolpattern64.c
  Symbol Patterns/symbolpattern65.c
  Symbol Patterns/symbolpattern66.c
  Symbol Patterns/symbolpattern67.c
  Symbol Patterns/symbolpattern68.c
  Symbol Patterns/symbolpattern69.c
  Symbol Patterns/symbolpattern70.c
Labels: SWoC-21, beginner

#903 40 symbol patterns added
  Symbol Patterns/symbolpattern111.c
  Symbol Patterns/symbolpattern112.c
  Symbol Patterns/symbolpattern113.c
  Symbol Patterns/symbolpattern114.c
  Symbol Patterns/symbolpattern115.c
  Symbol Patterns/symbolpattern116.c
  Symbol Patterns/symbolpattern117.c
  Symbol Patterns/symbolpattern118.c
  Symbol Patterns/symbolpattern119.c
  Symbol Patterns/symbolpattern120.c
  Symbol Patterns/symbolpattern121.c
  Symbol Patterns/symbolpattern122.c
  Symbol Patterns/symbolpattern123.c
  Symbol Patterns/symbolpattern124.c
  Symbol Patterns/symbolpattern125.c
  Symbol Patterns/symbolpattern126.c
  Symbol Patterns/symbolpattern127.c
  Symbol Patterns/symbolpattern128.c
  Symbol Patterns/symbolpattern129.c
  Symbol Patterns/symbolpattern130.c
  Symbol Patterns/symbolpattern131.c
  Symbol Patterns/symbolpattern132.c
  Symbol Patterns/symbolpattern133.c
  Symbol Patterns/symbolpattern134.c
  Symbol Patterns/symbolpattern135.c
  Symbol Patterns/symbolpattern136.c
  Symbol Patterns/symbolpattern137.c
  Symbol Patterns/symbolpattern138.c
  Symbol Patterns/symbolpattern139.c
  Symbol Patterns/symbolpattern140.c
  Symbol Patterns/symbolpattern141.c
  Symbol Patterns/symbolpattern142.c
  Symbol Patterns/symbolpattern143.c
  Symbol Patterns/symbolpattern144.c
  Symbol Patterns/symbolpattern145.c
  Symbol Patterns/symbolpattern146.c
  Symbol Patterns/symbolpattern147.c
  Symbol Patterns/symbolpattern148.c
  Symbol Patterns/symbolpattern149.c
  Symbol Patterns/symbolpattern150.c
Labels: SWoC-21, hard

#902 10 patterns added
  Alphabetic Patterns/alphabeticpattern36.c
  Alphabetic Patterns/alphabeticpattern37.c
  Alphabetic Patterns/alphabeticpattern38.c
  Alphabetic Patterns/alphabeticpattern39.c
  Alphabetic Patterns/alphabeticpattern43.c
  Alphabetic Patterns/alphabeticpattern44.c
  Alphabetic Patterns/alphabeticpattern45.c
  Alphabetic Patterns/alphabeticpattern46.c
  Alphabetic Patterns/alphabeticpattern48.c
  Alphabetic Patterns/alphabeticpattern70.c
Labels: SWoC-21, beginner

#904 20 patterns added
  Numeric Patterns/numericpattern100.c
  Numeric Patterns/numericpattern81.c
  Numeric Patterns/numericpattern82.c
  Numeric Patterns/numericpattern83.c
  Numeric Patterns/numericpattern84.c
  Numeric Patterns/numericpattern85.c
  Numeric Patterns/numericpattern86.c
  Numeric Patterns/numericpattern87.c
  Numeric Patterns/numericpattern88.c
  Numeric Patterns/numericpattern89.c
  Numeric Patterns/numericpattern90.c
  Numeric Patterns/numericpattern91.c
  Numeric Patterns/numericpattern92.c
  Numeric Patterns/numericpattern93.c
  Numeric Patterns/numericpattern94.c
  Numeric Patterns/numericpattern95.c
  Numeric Patterns/numericpattern96.c
  Numeric Patterns/numericpattern97.c
  Numeric Patterns/numericpattern98.c
  Numeric Patterns/numericpattern99.c
Labels: SWoC-21, easy

#905 40 patterns added
  Numeric Patterns/numericpattern181.c
  Numeric Patterns/numericpattern182.c
  Numeric Patterns/numericpattern183.c
  Numeric Patterns/numericpattern184.c
  Numeric Patterns/numericpattern185.c
  Numeric Patterns/numericpattern186.c
  Numeric Patterns/numericpattern187.c
  Numeric Patterns/numericpattern188.c
  Numeric Patterns/numericpattern189.c
  Numeric Patterns/numericpattern190.c
  Numeric Patterns/numericpattern191.c
  Numeric Patterns/numericpattern192.c
  Numeric Patterns/numericpattern193.c
  Numeric Patterns/numericpattern194.c
  Numeric Patterns/numericpattern195.c
  Numeric Patterns/numericpattern196.c
  Numeric Patterns/numericpattern197.c
  Numeric Patterns/numericpattern198.c
  Numeric Patterns/numericpattern199.c
  Numeric Patterns/numericpattern200.c
  Numeric Patterns/numericpattern201.c
  Numeric Patterns/numericpattern202.c
  Numeric Patterns/numericpattern203.c
  Numeric Patterns/numericpattern204.c
  Numeric Patterns/numericpattern205.c
  Numeric Patterns/numericpattern206.c
  Numeric Patterns/numericpattern207.c
  Numeric Patterns/numericpattern208.c
  Numeric Patterns/numericpattern209.c
  Numeric Patterns/numericpattern210.c
  Numeric Patterns/numericpattern211.c
  Numeric Patterns/numericpattern212.c
  Numeric Patterns/numericpattern213.c
  Numeric Patterns/numericpattern214.c
  Numeric Patterns/numericpattern215.c
  Numeric Patterns/numericpattern216.c
  Numeric Patterns/numericpattern217.c
  Numeric Patterns/numericpattern218.c
  Numeric Patterns/numericpattern219.c
  Numeric Patterns/numericpattern220.c
Labels: SWoC-21, hard

#907 20 patterns added
  Numeric Patterns/numericpattern163.c
  Numeric Patterns/numericpattern164.c
  Numeric Patterns/numericpattern165.c
  Numeric Patterns/numericpattern166.c
  Numeric Patterns/numericpattern170.c
  Numeric Patterns/numericpattern171.c
  Numeric Patterns/numericpattern172.c
  Numeric Patterns/numericpattern173.c
  Numeric Patterns/numericpattern174.c
  Numeric Patterns/numericpattern175.c
  Numeric Patterns/numericpattern221.c
  Numeric Patterns/numericpattern222.c
  Numeric Patterns/numericpattern223.c
  Numeric Patterns/numericpattern224.c
  Numeric Patterns/numericpattern225.c
  Numeric Patterns/numericpattern234.c
  Numeric Patterns/numericpattern271.c
  Numeric Patterns/numericpattern272.c
  Numeric Patterns/numericpattern303.c
  Numeric Patterns/numericpattern304.c
Labels: SWoC-21, easy

#906 40 patterns added
  Alphabetic Patterns/alphabeticpattern101.c
  Alphabetic Patterns/alphabeticpattern102.c
  Alphabetic Patterns/alphabeticpattern103.c
  Alphabetic Patterns/alphabeticpattern104.c
  Alphabetic Patterns/alphabeticpattern105.c
  Alphabetic Patterns/alphabeticpattern106.c
  Alphabetic Patterns/alphabeticpattern107.c
  Alphabetic Patterns/alphabeticpattern108.c
  Alphabetic Patterns/alphabeticpattern109.c
  Alphabetic Patterns/alphabeticpattern110.c
  Symbol Patterns/symbolpattern151.c
  Symbol Patterns/symbolpattern152.c
  Symbol Patterns/symbolpattern153.c
  Symbol Patterns/symbolpattern154.c
  Symbol Patterns/symbolpattern155.c
  Symbol Patterns/symbolpattern156.c
  Symbol Patterns/symbolpattern157.c
  Symbol Patterns/symbolpattern158.c
  Symbol Patterns/symbolpattern159.c
  Symbol Patterns/symbolpattern160.c
  Symbol Patterns/symbolpattern161.c
  Symbol Patterns/symbolpattern162.c
  Symbol Patterns/symbolpattern163.c
  Symbol Patterns/symbolpattern164.c
  Symbol Patterns/symbolpattern165.c
  Symbol Patterns/symbolpattern166.c
  Symbol Patterns/symbolpattern167.c
  Symbol Patterns/symbolpattern168.c
  Symbol Patterns/symbolpattern169.c
  Symbol Patterns/symbolpattern170.c
  Symbol Patterns/symbolpattern171.c
  Symbol Patterns/symbolpattern172.c
  Symbol Patterns/symbolpattern173.c
  Symbol Patterns/symbolpattern174.c
  Symbol Patterns/symbolpattern175.c
  Symbol Patterns/symbolpattern176.c
  Symbol Patterns/symbolpattern178.c
  Symbol Patterns/symbolpattern179.c
  Symbol Patterns/symbolpattern180.c
  Symbol Patterns/symolpaattern177.c
Labels: SWoC-21, hard

#908 10 patterns added
  Alphabetic Patterns/alphabeticpattern118.c
  Alphabetic Patterns/alphabeticpattern119.c
  Alphabetic Patterns/alphabeticpattern120.c
  Alphabetic Patterns/alphabeticpattern121.c
  Alphabetic Patterns/alphabeticpattern122.c
  Alphabetic Patterns/alphabeticpattern134.c
  Alphabetic Patterns/alphabeticpattern135.c
  Alphabetic Patterns/alphabeticpattern94.c
  Alphabetic Patterns/alphabeticpattern95.c
  Alphabetic Patterns/alphabeticpattern96.c
Labels: SWoC-21, beginner

#909 40 numeric patterns added
  Numeric Patterns/numericpattern287.c
  Numeric Patterns/numericpattern288.c
  Numeric Patterns/numericpattern289.c
  Numeric Patterns/numericpattern290.c
  Numeric Patterns/numericpattern291.c
  Numeric Patterns/numericpattern292.c
  Numeric Patterns/numericpattern293.c
  Numeric Patterns/numericpattern294.c
  Numeric Patterns/numericpattern295.c
  Numeric Patterns/numericpattern296.c
  Numeric Patterns/numericpattern297.c
  Numeric Patterns/numericpattern298.c
  Numeric Patterns/numericpattern299.c
  Numeric Patterns/numericpattern300.c
  Numeric Patterns/numericpattern301.c
  Numeric Patterns/numericpattern302.c
  Numeric Patterns/numericpattern305.c
  Numeric Patterns/numericpattern306.c
  Numeric Patterns/numericpattern307.c
  Numeric Patterns/numericpattern308.c
  Numeric Patterns/numericpattern309.c
  Numeric Patterns/numericpattern310.c
  Numeric Patterns/numericpattern311.c
  Numeric Patterns/numericpattern312.c
  Numeric Patterns/numericpattern313.c
  Numeric Patterns/numericpattern314.c
  Numeric Patterns/numericpattern315.c
  Numeric Patterns/numericpattern316.c
  Numeric Patterns/numericpattern317.c
  Numeric Patterns/numericpattern318.c
  Numeric Patterns/numericpattern319.c
  Numeric Patterns/numericpattern320.c
  Numeric Patterns/numericpattern321.c
  Numeric Patterns/numericpattern322.c
  Numeric Patterns/numericpattern323.c
  Numeric Patterns/numericpattern324.c
  Numeric Patterns/numericpattern325.c
  Numeric Patterns/numericpattern326.c
  Numeric Patterns/numericpattern327.c
  Numeric Patterns/numericpattern328.c
Labels: SWoC-21, hard

#912 40 Numeric patterns added
  Numeric Patterns/numericpattern245.c
  Numeric Patterns/numericpattern246.c
  Numeric Patterns/numericpattern247.c
  Numeric Patterns/numericpattern248.c
  Numeric Patterns/numericpattern249.c
  Numeric Patterns/numericpattern250.c
  Numeric Patterns/numericpattern251.c
  Numeric Patterns/numericpattern252.c
  Numeric Patterns/numericpattern253.c
  Numeric Patterns/numericpattern254.c
  Numeric Patterns/numericpattern255.c
  Numeric Patterns/numericpattern256.c
  Numeric Patterns/numericpattern257.c
  Numeric Patterns/numericpattern258.c
  Numeric Patterns/numericpattern259.c
  Numeric Patterns/numericpattern260.c
  Numeric Patterns/numericpattern261.c
  Numeric Patterns/numericpattern262.c
  Numeric Patterns/numericpattern263.c
  Numeric Patterns/numericpattern264.c
  Numeric Patterns/numericpattern265.c
  Numeric Patterns/numericpattern266.c
  Numeric Patterns/numericpattern267.c
  Numeric Patterns/numericpattern268.c
  Numeric Patterns/numericpattern269.c
  Numeric Patterns/numericpattern270.c
  Numeric Patterns/numericpattern273.c
  Numeric Patterns/numericpattern274.c
  Numeric Patterns/numericpattern275.c
  Numeric Patterns/numericpattern276.c
  Numeric Patterns/numericpattern277.c
  Numeric Patterns/numericpattern278.c
  Numeric Patterns/numericpattern279.c
  Numeric Patterns/numericpattern280.c
  Numeric Patterns/numericpattern281.c
  Numeric Patterns/numericpattern282.c
  Numeric Patterns/numericpattern283.c
  Numeric Patterns/numericpattern284.c
  Numeric Patterns/numericpattern285.c
  Numeric Patterns/numericpattern286.c
Labels: SWoC-21, hard

#913 10 patterns added
  Alphabetic Patterns/alphabeticpattern40.c
  Alphabetic Patterns/alphabeticpattern41.c
  Alphabetic Patterns/alphabeticpattern42.c
  Alphabetic Patterns/alphabeticpattern47.c
  Alphabetic Patterns/alphabeticpattern49.c
  Alphabetic Patterns/alphabeticpattern50.c
  Alphabetic Patterns/alphabeticpattern51.c
  Alphabetic Patterns/alphabeticpattern52.c
  Alphabetic Patterns/alphabeticpattern53.c
  Alphabetic Patterns/alphabeticpattern57.c
Labels: SWoC-21, beginner

#911 Added 40 patterns
  Numeric Patterns/numericpattern228.c
  Numeric Patterns/numericpattern229.c
  Numeric Patterns/numericpattern230.c
  Numeric Patterns/numericpattern231.c
  Numeric Patterns/numericpattern235.c
  Numeric Patterns/numericpattern236.c
  Numeric Patterns/numericpattern237.c
  Numeric Patterns/numericpattern238.c
  Numeric Patterns/numericpattern239.c
  Numeric Patterns/numericpattern240.c
  Numeric Patterns/numericpattern241.c
  Numeric Patterns/numericpattern242.c
  Numeric Patterns/numericpattern243.c
  Numeric Patterns/numericpattern244.c
  Symbol Patterns/symbolpattern181.c
  Symbol Patterns/symbolpattern182.c
  Symbol Patterns/symbolpattern183.c
  Symbol Patterns/symbolpattern184.c
  Symbol Patterns/symbolpattern185.c
  Symbol Patterns/symbolpattern186.c
  Symbol Patterns/symbolpattern187.c
  Symbol Patterns/symbolpattern188.c
  Symbol Patterns/symbolpattern189.c
  Symbol Patterns/symbolpattern190.c
  Symbol Patterns/symbolpattern191.c
  Symbol Patterns/symbolpattern192.c
  Symbol Patterns/symbolpattern193.c
  Symbol Patterns/symbolpattern194.c
  Symbol Patterns/symbolpattern195.c
  Symbol Patterns/symbolpattern196.c
  Symbol Patterns/symbolpattern197.c
  Symbol Patterns/symbolpattern198.c
  Symbol Patterns/symbolpattern199.c
  Symbol Patterns/symbolpattern200.c
  Symbol Patterns/symbolpattern201.c
  Symbol Patterns/symbolpattern202.c
  Symbol Patterns/symbolpattern203.c
  Symbol Patterns/symbolpattern204.c
  Symbol Patterns/symbolpattern205.c
  Symbol Patterns/symbolpattern206.c
Labels: SWoC-21, hard

#915 10 patterns added
  Alphabetic Patterns/alphabeticpattern54.c
  Alphabetic Patterns/alphabeticpattern55.c
  Alphabetic Patterns/alphabeticpattern56.c
  Alphabetic Patterns/alphabeticpattern67.c
  Alphabetic Patterns/alphabeticpattern68.c
  Alphabetic Patterns/alphabeticpattern69.c
  Alphabetic Patterns/alphabeticpattern71.c
  Alphabetic Patterns/alphabeticpattern97.c
  Alphabetic Patterns/alphabeticpattern98.c
  Alphabetic Patterns/alphabeticpattern99.c
Labels: SWoC-21, beginner

#916 10 alphabetic patterns added
  Alphabetic Patterns/alphabeticpattern157.c
  Alphabetic Patterns/alphabeticpattern158.c
  Alphabetic Patterns/alphabeticpattern159.c
  Alphabetic Patterns/alphabeticpattern160.c
  Alphabetic Patterns/alphabeticpattern161.c
  Alphabetic Patterns/alphabeticpattern162.c
  Alphabetic Patterns/alphabeticpattern163.c
  Alphabetic Patterns/alphabeticpattern164.c
  Alphabetic Patterns/alphabeticpattern165.c
  Alphabetic Patterns/alphabeticpattern166.c
Labels: SWoC-21, beginner

#917 40 patterns added
  Alphabetic Patterns/alphabeticpattern100.c
  Alphabetic Patterns/alphabeticpattern111.c
  Alphabetic Patterns/alphabeticpattern112.c
  Alphabetic Patterns/alphabeticpattern113.c
  Alphabetic Patterns/alphabeticpattern114.c
  Alphabetic Patterns/alphabeticpattern115.c
  Alphabetic Patterns/alphabeticpattern116.c
  Alphabetic Patterns/alphabeticpattern117.c
  Alphabetic Patterns/alphabeticpattern123.c
  Alphabetic Patterns/alphabeticpattern124.c
  Alphabetic Patterns/alphabeticpattern125.c
  Alphabetic Patterns/alphabeticpattern126.c
  Alphabetic Patterns/alphabeticpattern127.c
  Alphabetic Patterns/alphabeticpattern128.c
  Alphabetic Patterns/alphabeticpattern129.c
  Alphabetic Patterns/alphabeticpattern130.c
  Alphabetic Patterns/alphabeticpattern131.c
  Alphabetic Patterns/alphabeticpattern132.c
  Alphabetic Patterns/alphabeticpattern133.c
  Alphabetic Patterns/alphabeticpattern136.c
  Alphabetic Patterns/alphabeticpattern137.c
  Alphabetic Patterns/alphabeticpattern138.c
  Alphabetic Patterns/alphabeticpattern139.c
  Alphabetic Patterns/alphabeticpattern140.c
  Alphabetic Patterns/alphabeticpattern141.c
  Alphabetic Patterns/alphabeticpattern142.c
  Alphabetic Patterns/alphabeticpattern143.c
  Alphabetic Patterns/alphabeticpattern144.c
  Alphabetic Patterns/alphabeticpattern145.c
  Alphabetic Patterns/alphabeticpattern146.c
  Alphabetic Patterns/alphabeticpattern147.c
  Alphabetic Patterns/alphabeticpattern148.c
  Alphabetic Patterns/alphabeticpattern149.c
  Alphabetic Patterns/alphabeticpattern150.c
  Alphabetic Patterns/alphabeticpattern151.c
  Alphabetic Patterns/alphabeticpattern152.c
  Alphabetic Patterns/alphabeticpattern153.c
  Alphabetic Patterns/alphabeticpattern154.c
  Alphabetic Patterns/alphabeticpattern155.c
  Alphabetic Patterns/alphabeticpattern156.c
Labels: SWoC-21, hard
